# Generated by Django 5.2.7 on 2025-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
