# Generated by Django 5.2.7 on 2025-10-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='branch',
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.ManyToManyField(related_name='menu_items', to='restaurant.restaurant'),
        ),
    ]
