# Generated by Django 5.2.7 on 2025-10-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='spiciness',
            field=models.IntegerField(blank=True, choices=[(0, 'No spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Very Hot')]),
        ),
    ]
