# Generated by Django 5.2.7 on 2025-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_menu_spiciness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_image/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='spiciness',
            field=models.IntegerField(blank=True, choices=[(0, 'No spicy'), (1, 'Low'), (2, 'Medium'), (3, 'Hot'), (4, 'Very Hot')]),
        ),
    ]
