# Generated by Django 5.2.7 on 2025-10-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menu_image_alter_menu_spiciness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
