# Generated by Django 5.2.7 on 2025-10-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
