# Generated by Django 5.2.7 on 2025-10-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_cart_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'dish')},
        ),
    ]
